driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    require_chef_omnibus: '11.14'
- name: ubuntu-14.04
  driver_config:
    require_chef_omnibus: '11.14'
- name: centos-5.11
  driver_config:
    require_chef_omnibus: '11.14'
- name: centos-6.7
  driver_config:
    require_chef_omnibus: '11.14'
- name: centos-7.1
  driver_config:
    require_chef_omnibus: '11.14'  
  
suites:
- name: default
  run_list:
  - recipe[omnibus_updater_test::default]
- name: upgrade
  run_list:
  - recipe[omnibus_updater_test::version_upgrade]
